#! /usr/bin/env bash

# 깃허브 조직의 팀 정보 조회
ORG=$(./read-properties -n ORG -f ./github-org.properties -d "=")
TOKEN=$(./read-properties -n YOUR_TOKEN -f ./github-org.properties -d "=")

team_slug='${Team_slug}'
username='${user_name}'

curl -L \
  -X PUT \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer $TOKEN" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/orgs/$ORG/teams/$team_slug/memberships/$username
